function (arBundle lib)
  set(FILE ${CMAKE_CURRENT_BINARY_DIR}/bundle.mri)
  file(WRITE ${FILE} "CREATE ${lib}\n")
  foreach(lib ${ARGN})
    file(APPEND ${FILE} "ADDLIB ${lib}\n")
  endforeach()
  file(APPEND ${FILE} "SAVE\n")
  file(APPEND ${FILE} "END")
endfunction()
